### PR TITLE
Our Apps section: appearance improved

### LINKED ISSUE #8: Write and use e2e test
Simple test to open web page in the browser and see no errors (no exceptions)

This will turn CI semaphore green

### LINKED ISSUE #9: Rework contact form
We want to get notified about people who submitted our form.

Two options applicable:

* e-mail
* slack message

### LINKED ISSUE #19: Drop IE and MS Edge support
We actually want to support latest 2 versions of android's Chrome and iOS's Safari

### PR DESCRIPTION
**Pull request by keshan3262**
closes #19 
closes #9 
closes #8

### CODE REVIEW

File: src/components/Screens/OurApps.js [hunk 1]
```diff
@@ -32,6 +60,7 @@ class OurApps extends React.Component {
         return {icon, description, screenshotUrls, name, url, bundleId};
       });
     }).then(extract => {
+      console.log(JSON.stringify(extract));
```
Comment (ColCh) [inline src/components/Screens/OurApps.js]: Remove console.log

File: src/components/Screens/OurApps.js [hunk 2]
```diff
@@ -7,7 +7,35 @@ import "src/styles/Screens/OurApps.css";
 const settings = {
   wrapAround: true,
   speed: 500,
-  slidesToShow: 1
+  slidesToShow: 1,
+  decorators: [{
+    component: React.createClass({
```
Comment (ColCh) [inline src/components/Screens/OurApps.js]: Refactor this inline component into separate entity file under`src/components/` and give it a name.

**Review by ColCh — CHANGES_REQUESTED** [review]
remove console.log and refactor inline component out into separate file
